### ISSUE TITLE
[WEBGL][iOS] Project not working

### ISSUE THREAD

**Issue by tng2903** [zappar-xr/unity-example-instant-tracking-3d-model#1]
Trying to use the current project at commit https://github.com/zappar-xr/unity-example-instant-tracking-3d-model/commit/5f62fbcef0521d7ec2c036313b3a8073795606b9 produced a web page that's not working on iOS
Trying to open it shown the error related to ZCV can't be found

**Comment by nfynt-zap** [comment]
This should have been fixed now! Do give the new release a try.
